Study Material/Semester 6/DB/Theory/Project/Final/WebApplication1/WebApplication1/Controllers/SemesterController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Classes;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class SemesterController : Controller
    {
        public JsonResult LoadAllCourses()
        {
            DB11V2Entities db = new DB11V2Entities();
            //IEnumerable<GetProducts_Result> res = db.GetProducts();
            List<Course> res = db.Courses.ToList();
            return Json(res.Select(x => new
            {
                ID = x.ID,
                Name = x.Name
            }));
        }
        public JsonResult LoadBatches()
        {
            DB11V2Entities db = new DB11V2Entities();
            //IEnumerable<GetProducts_Result> res = db.GetProducts();
            List<Batch> res = db.Batches.ToList();
            return Json(res.Select(x => new
            {
                ID = x.ID,
                Name = x.Session
            }));
        }

        public JsonResult LoadSemester(int item)
        {
            DB11V2Entities db = new DB11V2Entities();
            //IEnumerable<GetProducts_Result> res = db.GetProducts();
            List<Semester> res = db.Semesters.Where(s=>s.BatchID == item).ToList();
            return Json(res.Select(x => new
            {
                ID = x.ID,
                Name = x.Name
            }));
        }

        public JsonResult LoadCourses()
        {
            DB11V2Entities db = new DB11V2Entities();
            //IEnumerable<GetProducts_Result> res = db.GetProducts();
            List<Course> res = db.Courses.ToList();
            return Json(res.Select(x => new
            {
                ID = x.ID,
                Name = x.Name
            }));
        }

        public JsonResult LoadSemesterCourses(int semesterID)
        {
            //IEnumerable<GetProducts_Result> res = db.GetProducts();
            List<Course> courseList = new List<Course>();
            SqlDataReader reader;
            string cmd = "SELECT * FROM Course WHERE Course.ID IN (SELECT CourseID FROM CourseSemester_MTM WHERE SemesterID = "+semesterID+")";
            reader = dbConnection.getInstance().getData(cmd);
            while(reader.Read())
            {
                Course c = new Course();
                c.ID = reader.GetInt32(0);
                c.Name = reader.GetString(1);
                courseList.Add(c);
            }
            return Json(courseList.Select(x => new
            {
                ID = x.ID,
                Name = x.Name
            }));
        }
        // GET: Semester
        public ActionResult Index()
        {
            return View();
        }

        // GET: Semester/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Semester/Create
        public ActionResult Create(int id)
        {
            DB11V2Entities db = new DB11V2Entities();
            Semester sm = db.Semesters.Where(s => s.ID == id).FirstOrDefault();

            ViewBag.batch = db.Batches.Where(b => b.ID == sm.BatchID).FirstOrDefault().Session;
            ViewBag.semester = sm.Name;
            ViewBag.semesterID = sm.ID;

            return View();
        }

        // POST: Semester/Create
        [HttpPost]
        public ActionResult Create(int id, CourseSemester_MTM collection)
        {
            DB11V2Entities db = new DB11V2Entities();
            Semester sm = db.Semesters.Where(s => s.ID == id).FirstOrDefault();

            ViewBag.batch = db.Batches.Where(b => b.ID == sm.BatchID).FirstOrDefault().Session;
            ViewBag.semester = sm.Name;
            ViewBag.semesterID = sm.ID;

            bool result = CourseSemesterAction.Create(id, collection.CourseID);
            if (result)
            {
                ViewBag.color = "green";
                ViewBag.message = "Course Added Successfully";
            }
            else
            {
                ViewBag.color = "red";
                ViewBag.message = "Course Already Exists";
            }
            return View();
        }

        // GET: Semester/Edit/5
        public ActionResult Edit(int sid, int cid)
        {
            DB11V2Entities db = new DB11V2Entities();
            Course c = db.Courses.Where(temp => temp.ID == cid).FirstOrDefault();
            return View(c);
        }

        // POST: Semester/Edit/5
        [HttpPost]
        public ActionResult Edit(int sid, int cid, Course collection)
        {
            bool result = CourseSemesterAction.Edit(sid, cid, collection);
            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.color = "red";
                ViewBag.message = "Course Already Exists";
                return View();
            }
        }

        // GET: Semester/Delete/5
        public ActionResult Delete(int sid, int cid)
        {
            DB11V2Entities db = new DB11V2Entities();
            Course cs = db.Courses.Where(c => c.ID == cid).FirstOrDefault();
            return View(cs);
        }

        // POST: Semester/Delete/5
        [HttpPost]
        public ActionResult Delete(int sid, int cid, FormCollection collection)
        {
            try
            {
                CourseSemesterAction.Delete(sid, cid);
                return RedirectToAction("Index");
            }
            catch
            {
                DB11V2Entities db = new DB11V2Entities();
                Course cs = db.Courses.Where(c => c.ID == cid).FirstOrDefault();

                ViewBag.color = "red";
                ViewBag.message = "Can't Delete";

                return View(cs);
            }
        }
    }
}

Study Material/Semester 6/DB/Theory/Project/Final/WebApplication1/WebApplication1/Views/Semester/Create.cshtml
@model WebApplication1.CourseSemester_MTM

@{
    ViewBag.Title = "Create";
}

<br>
<br>
<h2>Add Course</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            <dl class="dl-horizontal">
                <dt>Batch</dt>
                <dd>@ViewBag.batch</dd>
                <dt>Semester</dt>
                <dd>@ViewBag.semester</dd>
            </dl>
        </div>
        <select id="selectCourse" name="CourseID" class="form-control" >
            <option></option>
        </select>
        <select name="SemesterID" class="form-control" style="display: none;">
            <option value="@ViewBag.semesterID">@ViewBag.semesterID</option>
        </select>
        <div class="form-group">
            <div class="col-md-10">
                <input @*id="btnCreate"*@ type="submit" value="Add Course" class="btn btn-default" />
            </div>
        </div>
        @{ if (ViewBag.color == "green")
            {
                <div class="alert alert-success">
                    <strong>Success!</strong> @ViewBag.message
                </div>
            }
            else if (ViewBag.color == "red")
            {
                <div class="alert alert-danger">
                    <strong>Error!</strong> @ViewBag.message
                </div>
            }
        }
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            getCourses();
        });
        $("#btnCreate").click(function () {
            window.location = "/Semester/Create?id=" + $("#Semester").val() + "&cid=" + $("#selectCourse option:selected").val();
        });

        function getCourses()
        {
            var d = {};
            d.url = '@Url.Action("LoadAllCourses", "Semester")';
            d.type = "POST";
            d.dataType = "json";
            d.contentType = "application/json";
            d.success = function (r) {
                $("#selectCourse").empty();
                $("#selectCourse").prepend("option value='' selected='selected'></option>");
                for (var i = 0; i < r.length; i++) {
                    $("#selectCourse").append('<option value="' + r[i].ID + '">' + r[i].Name + '</option>');
                }
            };
            $.ajax(d);
        }
    </script>
}

Study Material/Semester 6/DB/Theory/Project/Final/WebApplication1/WebApplication1/Views/Semester/Delete.cshtml
@model WebApplication1.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
    @{ if (ViewBag.color == "green")
            {
            <div class="alert alert-success">
                <strong>Success!</strong> @ViewBag.message
            </div>
        }
        else if (ViewBag.color == "red")
        {
            <div class="alert alert-danger">
                <strong>Error!</strong> @ViewBag.message
            </div>
        }
    }
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Study Material/Semester 6/DB/Theory/Project/Final/WebApplication1/WebApplication1/Views/Semester/Edit.cshtml
@model WebApplication1.Course

@{
    ViewBag.Title = "Edit";
}

<br>
<br>
<h2>Edit Semester Courses</h2>
<hr>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2">Batch</label>
            <div class="col-md-10">
                <select id="Course" name="ID" class="form-control" style="float: left;">
                    <option></option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
        @{ if (ViewBag.color == "green")
            {
                <div class="alert alert-success">
                    <strong>Success!</strong> @ViewBag.message
                </div>
            }
            else if (ViewBag.color == "red")
            {
                <div class="alert alert-danger">
                    <strong>Error!</strong> @ViewBag.message
                </div>
            }
        }
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $.when($.ajax(loadCourses())).then(function () {
                setDefault("Course", @Model.ID);
            });
        });

        function loadCourses()
        {
            debugger;
            event.preventDefault();
            var $url = '/Semester/LoadCourses';
            //alert($url);

            $.ajax({
                url: $url,
                type: 'POST',
                datatype: "json",
                data: jQuery.param({
                    //item: $("#Batch option:selected").val(),
                }),
                success: function (r) {
                    $("#Course").empty();
                    $("#Course").prepend("option value='' selected='selected'></option>");
                    for (var i = 0; i < r.length; i++) {
                        $("#Course").append('<option value="' + r[i].ID + '">' + r[i].Name + '</option>');
                    }
                }
            });
        }

        function setDefault(id, itemId) {
            var selectobject = document.getElementById(id);

            for (var i, j = 0; i = selectobject.options[j]; j++) {
                if (i.value == itemId) {
                    selectobject.selectedIndex = j;
                    break;
                }
            }
        }
    </script>

}

Study Material/Semester 6/DB/Theory/Project/Final/WebApplication1/WebApplication1/Views/Semester/Index.cshtml
@model IEnumerable<WebApplication1.Course>

@{
    ViewBag.Title = "Index";
}

<br>
<br>
<h2>Semester Index</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2">Batch</label>
            <div class="col-md-10">
                <select id="Batch" name="BatchId" class="form-control" style="float: left;">
                    <option></option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Semester</label>
            <div class="col-md-10">
                <select id="Semester" class="form-control">
                    <option></option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="btnSubmit" type="button" value="List Registered Courses" class="btn btn-default" />
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input id="btnCreate" type="button" value="Add Courses" class="btn btn-default" />
            </div>
        </div>
    </div>

    <table class="table table-bordered" id="courseTable">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
    </table>
}

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function (e) {
            getBatches();
        });
        $("#Batch").change(function () {
            getSemesters();
        });
        $("#btnSubmit").click(function () {
            showCourses();
        });
        $("#btnCreate").click(function () {
            window.location = "/Semester/Create?id=" + $("#Semester option:selected").val();
        });

        function getBatches()
        {
            var d = {};
            d.url = '@Url.Action("LoadBatches", "Semester")';
            d.type = "POST";
            d.dataType = "json";
            d.contentType = "application/json";
            d.success = function (r) {
                $("#Batch").empty();
                $("#Batch").prepend("option value='' selected='selected'></option>");
                for (var i = 0; i < r.length; i++) {
                    $("#Batch").append('<option value="' + r[i].ID + '">' + r[i].Name + '</option>');
                }
                getSemesters();
            };
            $.ajax(d);
        }

        function getSemesters()
        {
            debugger;
            event.preventDefault();
            var $url = '/Semester/LoadSemester';
            //alert($url);

            $.ajax({
                url: $url,
                type: 'POST',
                datatype: "json",
                data: jQuery.param({
                    item: $("#Batch option:selected").val(),
                }),
                success: function (r) {
                    $("#Semester").empty();
                    $("#Semester").prepend("option value='' selected='selected'></option>");
                    for (var i = 0; i < r.length; i++) {
                        $("#Semester").append('<option value="' + r[i].ID + '">' + r[i].Name + '</option>');
                    }
                }
            });
        }

        function showCourses()
        {
            debugger;
            event.preventDefault();
            var $url = '/Semester/LoadSemesterCourses';

            $.ajax({
                url: $url,
                type: 'POST',
                datatype: "json",
                data: jQuery.param({
                    semesterID: $("#Semester option:selected").val()
                }),
                success: function (r) {
                    $("#courseTable #dataRow").remove();
                    for (var i = 0; i < r.length; i++) {
                        $("#courseTable").append(
                            "<tr id='dataRow'>" +
                            "<td>" + r[i].Name + "</td>" +
                            "<td><a href=/Semester/Edit/?sid=" + $("#Semester option:selected").val() + "&cid=" + r[i].ID + ">Edit</a> | " +
                            "<a href=/Semester/Delete/?sid=" + $("#Semester option:selected").val() + "&cid=" + r[i].ID + ">Delete</a></td>" +
                            "</tr>"
                            );
                    }
                }
            });
        }
    </script>
}