Study Material/Internship/IbmAdmissions2019/IbmAdmissions2019/Controllers/StudentAdmissionController.cs
using CrystalDecisions.CrystalReports.Engine;
using IbmAdmissions2019.Models;
using IbmAdmissions2019.Utilities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IbmAdmissions2019.Controllers
{
    public class StudentAdmissionController : Controller
    {
        public JsonResult getProvinceList()
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            //IEnumerable<GetProducts_Result> res = db.GetProducts();
            int placeLevel = db.Lookups.Where(temp => temp.LookupName.Equals("Province")).FirstOrDefault().LookupId;
            List<City> result = db.Cities.Where(temp => temp.PlaceLevel == placeLevel).ToList();
            return Json(result.Select(x => new
            {
                ID = x.Id,
                Name = x.Name
            }));
        }

        public JsonResult getDistrictList(int itemId)
        {

            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            //IEnumerable<GetProducts_Result> res = db.GetProducts();
            int placeLevel = db.Lookups.Where(temp => temp.LookupName.Equals("District")).FirstOrDefault().LookupId;
            List<City> result = db.Cities.Where(temp => temp.PlaceLevel == placeLevel && temp.ParentId == itemId).ToList();
            return Json(result.Select(x => new
            {
                ID = x.Id,
                Name = x.Name
            }));
        }
        public JsonResult getCityList(int itemId)
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            //IEnumerable<GetProducts_Result> res = db.GetProducts();
            int placeLevel = db.Lookups.Where(temp => temp.LookupName.Equals("City")).FirstOrDefault().LookupId;
            List<City> result = db.Cities.Where(temp => temp.PlaceLevel == placeLevel && temp.ParentId == itemId).ToList();
            return Json(result.Select(x => new
            {
                ID = x.Id,
                Name = x.Name
            }));
        }
        public JsonResult getDegreeList()
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            List<Degree> result = db.Degrees.ToList();
            return Json(result.Select(x => new
            {
                ID = x.DegreeId,
                Name = x.DegreeName
            }));
        }
        public JsonResult getProgramList(int itemId)
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            List<Program> result = db.Programs.Where(temp => temp.DegreeId == itemId).ToList();
            return Json(result.Select(x => new CheckBoxListItem()
            {
                ID = x.ProgramId,
                Display = x.ProgramName,
                IsChecked = false
            }));
        }
        //public JsonResult getEducationDetailList(int itemId)
        //{
        //    IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
        //    List<EducationDetail> result = db.EducationDetails.Where(temp=>temp.EducationLevel == itemId).ToList();
        //    return Json(result.Select(x => new
        //    {
        //        ID = x.EducationId,
        //        Name = x.EducationName
        //    }));
        //}
        public JsonResult getGenderList()
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            List<Lookup> result = db.Lookups.Where(temp => temp.CategoryName.Equals("Gender")).ToList();
            return Json(result.Select(x => new
            {
                ID = x.LookupId,
                Name = x.LookupName
            }));
        }


        public List<SelectListItem> getGenderSelectList()
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            var result = db.Lookups.Where(temp => temp.CategoryName.Equals("Gender"))
                .Select(v => new SelectListItem() {
                    Text = v.LookupName,
                    Value = v.LookupId + ""
                }).ToList();
            return result;
        }
        public List<SelectListItem> getProvinceSelectList()
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            int placeLevel = db.Lookups.Where(temp => temp.LookupName.Equals("Province")).FirstOrDefault().LookupId;

            var result = db.Cities.Where(temp => temp.PlaceLevel == placeLevel)
                .Select(v => new SelectListItem()
                {
                    Text = v.Name,
                    Value = v.Id + ""
                }).ToList();
            return result;
        }
        public List<SelectListItem> getDistrictSelectList()
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            int placeLevel = db.Lookups.Where(temp => temp.LookupName.Equals("District")).FirstOrDefault().LookupId;

            var result = db.Cities.Where(temp => temp.PlaceLevel == placeLevel)
                .Select(v => new SelectListItem()
                {
                    Text = v.Name,
                    Value = v.Id + ""
                }).ToList();
            return result;
        }
        public List<SelectListItem> getCitySelectList()
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            int placeLevel = db.Lookups.Where(temp => temp.LookupName.Equals("City")).FirstOrDefault().LookupId;

            var result = db.Cities.Where(temp => temp.PlaceLevel == placeLevel)
                .Select(v => new SelectListItem()
                {
                    Text = v.Name,
                    Value = v.Id + ""
                }).ToList();
            return result;
        }
        public List<SelectListItem> getDegreeSelectList()
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            var result = db.Degrees
                .Select(v => new SelectListItem()
                {
                    Text = v.DegreeName,
                    Value = v.DegreeId + ""
                }).ToList();
            return result;
        }
        public List<SelectListItem> getProgramSelectList(int degreeId)
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            var result = db.Programs.Where(a => a.DegreeId == degreeId)
                .Select(v => new SelectListItem()
                {
                    Text = v.ProgramName,
                    Value = v.ProgramId + ""
                }).ToList();
            return result;
        }
        public List<SelectListItem> getProgramSelectList(int degreeId, int studentId)
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            List<int> StudentProgramIds = db.StudentPrograms.Where(a => a.StudentId == studentId).Select(v => v.ProgramId).ToList();
            List<Program> ProgramList = db.Programs.Where(a => a.DegreeId == degreeId).ToList();
            List<SelectListItem> result = new List<SelectListItem>();
            foreach (Program pr in ProgramList)
            {
                SelectListItem sli = new SelectListItem();
                if (StudentProgramIds.Contains(pr.ProgramId))
                {
                    sli.Selected = true;
                }
                sli.Text = pr.ProgramName;
                sli.Value = pr.ProgramId + "";
                result.Add(sli);
            }

            return result;
        }
        public List<SelectListItem> getEducationDetailSelectList(int educationId)
        {

            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            int educationLevel = 0;
            if (educationId > 0) educationLevel = db.EducationDetails.Where(a => a.EducationId == educationId).FirstOrDefault().EducationLevel;
            var result = db.EducationDetails.Where(a => a.EducationLevel == educationLevel)
                .Select(v => new SelectListItem()
                {
                    Text = v.EducationName,
                    Value = v.EducationId + ""
                }).ToList();
            return result;
        }
        public List<SelectListItem> getEducationDetailSelectListByLvl(int educationLevel)
        {

            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();

            var result = db.EducationDetails.Where(a => a.EducationLevel == educationLevel)
                .Select(v => new SelectListItem()
                {
                    Text = v.EducationName,
                    Value = v.EducationId + ""
                }).ToList();
            return result;
        }
        public EducationItem getBachEducationItem(string cnic)
        {
            IbmAdmissions2019Entities db = new IbmAdmissions2019Entities();
            var st = db.Students.Where(a => a.StudentCnic.Equals(cnic)).FirstOrDefault();
            if (st == null)
            {
                int bachId = db.Lookups.Where(a => a.LookupName.Equals("Bachelor")).FirstOrDefault().LookupId;
                int[] bachIds = db.EducationDetails.Where(a => a.EducationLevel == bachId).Select(a => a.EducationId).ToArray();

                EducationItem ed = new EducationItem();
                ed.Id = bachId;
                ed.educationDetail = 0;
                ed.obtained = 0;
                ed.total = 0;
                ed.degreeCompleted = false;
                ed.pointType = 0;
                ed.pointTypeList = getPointsType();
                ed.label = "Bachelor/Master (16 year education)";
                ed.courseList = getEducationDetailSelectListByLvl(bachId);

                return ed;
            }
            else
            {
                List<StudentEducation> edList = db.StudentEducations.Where(a => a.StudentId == st.Id).ToList();

Study Material/Internship/IbmAdmissions2019/IbmAdmissions2019/Views/StudentAdmission/GetStudentDetails.cshtml
@model IbmAdmissions2019.Models.StudentViewModels

<div>
    <h4>StudentViewModels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fatherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fatherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fatherCNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fatherCNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.perAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.perAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.religion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.religion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.province)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.province)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.district)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.district)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.districtName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.districtName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.provinceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.provinceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.homePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.homePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cellNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cellNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.degree)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.degree)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.program)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.program)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.educationDetailFirst)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.educationDetailFirst)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.educationDetailFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.educationDetailFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstYrMarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstYrMarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstYrTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstYrTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.finalMarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.finalMarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.finalTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.finalTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bachEducationDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bachEducationDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bachMarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bachMarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bachTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bachTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.trackingNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trackingNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Study Material/Internship/IbmAdmissions2019/IbmAdmissions2019/Views/StudentAdmission/PrintApplicationForms.cshtml
@{
    ViewBag.Title = "PrintApplicationForms";
}



@{
    var list = (List<IbmAdmissions2019.Models.ProgramsAppliedFor>)(ViewBag.ProgramList);
}

<div class="justify-content-center d-flex">
    <h2>Appication Forms</h2>
</div>
<h6 class="justify-content-center d-flex">Print application forms for all of your applied programs</h6>


<ul class="list-group">



    @foreach (var c in list)
    {

        <li class="list-group-item">
            <a href="/StudentAdmission/PrintApplicationForm/@c.Id">
                <div class="md-v-line"></div><i class="fas fa-download mr-4 pr-3"></i> @c.ProgramName
            </a>
        </li>


    }
</ul>

Study Material/Internship/IbmAdmissions2019/IbmAdmissions2019/Views/StudentAdmission/StudentPhotograph.cshtml
@{
    ViewBag.Title = "StudentPhotograph";
}


@{
    bool flag = false;
    String msg = "";
    if (ViewBag.PicMessage != null)
    {
        msg = (String)ViewBag.PicMessage;
        flag = true;
    }
}


@if (flag)
{
    <div class="alert alert-danger" id="errMsg" role="alert">
        @ViewBag.PicMessage
    </div>
}
else
{
  
        <div class="alert alert-danger d-none" id="errMsg" role="alert">
             
        </div>
  
}
@using (Html.BeginForm("StudentPhotograph", "StudentAdmission", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{

    <div class="row">
        <div class="col-md-4" style="height:300px">
            <img id="stdImg" width="270" height="300" src="@IbmAdmissions2019.Utilities.StudentUtility.getInstance().getImagePath(User.Identity.Name)" />
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-6">
            <br />
            <br />
            <h4>Instructions</h4>
            <ul>
                <li>
                    Upload passport size photograph
                </li>
                <li>
                    Maximum allowed file size is 1MB.
                </li>
                <li>
                    This photograph will be used as photo identity in test center
                </li>
            </ul>

        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <label for="file">Upload Image</label>
            <input type="file" id="file" class="form-control-file" name="file" onchange="readURL(this)" accept="image/gif, image/jpeg, image/png" />
        </div>

    </div>
    <div class="row d-flex justify-content-right">
        <input type="submit" class="btn btn-primary" value="Upload" />
    </div>




}
<script>
    function readURL(input) {

        if (input.files && input.files[0]) {

            var size = input.files[0].size;

            if (size > 1024000) {
                $("#file").val("");
                $("#errMsg").html("Maximum file size exceeds. Maximum allowed file size is 1MB.");
                $("#errMsg").removeClass("d-none");
                return;
            }
            else {
                var reader = new FileReader();
                $("#errMsg").addClass("d-none");
                reader.onload = function (e) {
                    $('#stdImg')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    }
</script>

Study Material/Internship/IbmAdmissions2019/IbmAdmissions2019/Views/StudentAdmission/getSt.cshtml
@model IbmAdmissions2019.Models.StudentViewModels

@{
    ViewBag.Title = "getSt";
}

<br/>
<div class="justify-content-center d-flex">
    <h2>Payment Confirmation</h2>
</div>
<h6 class="justify-content-center d-flex">Confirm challan form payment of student</h6>
<br/>
@using (Html.BeginForm())
{
    <div class=" form-group row d-flex justify-content-center" >
        <div class="col-md-4">
            <label>Tracking Number</label>


            <input type="text" name="tno" id="keyword" class="form-control" />
        </div>
     
    </div>
   
        <div class="form-group row  d-flex justify-content-center">
            <div class="col-md-4 d-flex justify-content-end" >
                <input type="submit" id="btnDisplaySearchResults" value="Search" class="btn btn-primary" />
            </div>
        </div>
   
}

@{
    String trackNum = "";
    if ((bool)ViewBag.flag)
    {
        trackNum = (int?)(ViewBag.TrackingNumber) + "";
    }
}

@if ((bool)ViewBag.flag)
{
        <div>
            <hr />
            <h3>Current Status</h3>
           
            <div class="row">
                <div class="col-md-2">
                    <span class="display">Status</span>
                </div>
                <div class="col-md-4">
                    @Html.DisplayFor(model => model.Status)
                </div>
                </div>
               
            </div>
    if (!Model.Status.Contains("found"))
    {
            <div>

                <h3>Student Details</h3>
          
                <div class="row">
                    <div class="col-md-2">
                        <span class="display">@Html.DisplayNameFor(model => model.name)</span>
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.name)
                    </div>
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.cNIC)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.cNIC)
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.fatherName)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.fatherName)
                    </div>
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.fatherCNIC)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.fatherCNIC)
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.dOB)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.dOB)
                    </div>
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.genderName)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.genderName)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.cellNo)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.cellNo)
                    </div>
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.homePhone)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.homePhone)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.religion)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.religion)
                    </div>
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.cityName)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.cityName)
                    </div>
                </div>
            </div>

            <br />
            if (!Model.Status.Contains("Already"))
            {
            <div class="d-flex justify-content-center">
                <a href="/StudentAdmission/ConfirmPayment?tno=@(trackNum)" class="btn btn-primary">Confirm Payment  </a>
            </div>
                }
            }
}

            <script>
    //@*var url = '@Url.Action("getStudentDetails", "StudentAdmission")';
    $('#search').click(function () {
        var keyWord = $('#Keyword').val();
        $('#GetStudentDetails').load(url, { TrackingNumber: keyWord });
    })*@
            </script>

Study Material/Internship/IbmAdmissions2019/IbmAdmissions2019/Views/StudentAdmission/getStudentsDetail.cshtml
@model IbmAdmissions2019.Models.StudentDetailsViewModel

@{
    ViewBag.Title = "getStudentsDetail";
}
<div class="justify-content-center d-flex">
    <h2>Student Credentials</h2>
</div>
<h6 class="justify-content-center d-flex">Check student credentials</h6>
<div>
    <hr />
    @using (Html.BeginForm())
    {

        <div class="form-group row d-flex justify-content-center">
            <div class="col-md-4">
                <label>CNIC</label>
                <input type="text" name="cnic" class="form-control" />
            </div>

        </div>
        <div class="form-group row d-flex justify-content-center">
            <div class="col-md-4">
                <label>Tracking Number</label>
                <input type="text" name="tno" class="form-control" />
            </div>
            </div>

            <div class="form-group row  d-flex justify-content-center">
                <div class="col-md-4 d-flex justify-content-end">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </div>

            }
            @if ((bool)ViewBag.flag &&(bool)ViewBag.status)
            {
                <div class="row">
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.CNIC)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.CNIC)
                    </div>
                    <div class="col-md-2">
                        @Html.DisplayNameFor(model => model.Email)
                    </div>
                    <div class="col-md-4">
                        @Html.DisplayFor(model => model.Email)
                    </div>
                </div>

            }
            else
            {
                <div class="text-danger d justify-content-center">
                    @ViewBag.St
                </div>
               
            }
        </div>